version: "3.7"

services:
  thelounge:
    image: thelounge/thelounge:alpine
    container_name: thelounge
    restart: unless-stopped
    volumes:
      - /mnt/slab/thelounge:/var/opt/thelounge
    networks:
      - backend

networks:
  backend:
    external:
      name: backend

