version: "3.5"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - certbot
    networks:
      - backend
  certbot:
    build: certbot
    restart: on-failure:3
    container_name: certbot
    env_file: ./certbot/.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    external: 
      name: backend
