version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - ./nginx:/etc/nginx
      - letsencrypt-data:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - letsencrypt
    networks:
      - backend
  letsencrypt:
    image: adferrand/letsencrypt-dns
    restart: always
    container_name: letsencrypt
    env_file: ./letsencrypt/.env
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - ./letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
    networks:
      - backend

volumes:
  letsencrypt-data:

networks:
  backend:
    external: 
      name: backend

