version: '3.5'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - /mnt/slab/jenkins:/var/jenkins_home
    networks:
      - backend

networks:
  backend:
    external: 
      name: backend

